server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:commercebank
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Disable mail for now (we'll enable later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fakecommercebank@gmail.com
spring.mail.password=rlthrfxarvbslwsn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
